### ISSUE TITLE
500 error on certain courses

### ISSUE THREAD

**Issue by MaggieAppleton** [eggheadio/og-image-egghead#3]
I'm getting an error when I try to generate images for certain courses. Weirdly it's not happening with all the course... only some.

![image](https://user-images.githubusercontent.com/5599295/73137835-51154380-4054-11ea-94b4-e2fe474ec1c3.png)

Tested a couple but don't see a particular pattern...

These work: 
- https://og-image-egghead-course.now.sh/shareable-custom-hooks-in-react
- https://og-image-egghead-course.now.sh/graphql-query-language

These don't:
- https://og-image-egghead-course.now.sh/introduction-to-state-machines-using-xstate
- https://og-image-egghead-course.now.sh/advanced-angular-component-patterns
- https://og-image-egghead-course.now.sh/learn-http-in-angular
- https://og-image-egghead-course.now.sh/gatsby-theme-authoring

**Comment by vojtaholik** [comment]
Fixed! :)
